package com.orangeskill.elate.framework.preference;



public interface IPrefrenceHelperKeys {

    // Shared preferences file name
    String PREF_NAME = "Welcome";
    String IS_FIRST_TIME_LAUNCH = "IsFirstTimeLaunch";

    String PREFS_FILE_NAME = "Windstream_prefrence_file";

    String PREFS_BILLING_SUMMARY_ACCOUNT = "PREFS_BILLING_SUMMARY_ACCOUNT";

    String PREFS_PRIMARY_USER_EXT = "PREFS_PRIMARY_USER_EXT";

    String PREFS_VOICEMAIL_USER_SETTING = "PREFS_VOICEMAIL_USER_SETTING";

    String PREFS_PRIMARY_DEVICE_LIST = "PREFS_PRIMARY_DEVICE_LIST";



    String PREFS_USER_EXTENSION_LIST = "PREFS_USER_EXTENSION_LIST";

    String PREFS_USER_PROFILE_URI = "PREFS_USER_PROFILE_URI";

    String PREFS_ADVOCATE_PROFILE_URI = "PREFS_ADVOCATE_PROFILE_URI";

    String PREFS_TODAY_DATE = "PREFS_TODAY_DATE";

    String PREFS_OFFICE_SUITE_USER = "PREFS_OFFICE_SUITE_USER";

    String PREFS_ACCOUNT_TYPE = "PREFS_ACCOUNT_TYPE";

    String PREFS_PRIMARY_USER_NAME = "PREFS_PRIMARY_USER_NAME";

    String PREFS_APP_ID = "PREFS_APP_ID";

    String PREFS_ONBOARDING_STARTUP= "PREFS_ONBOARDING_STARTUP";

    String PREFS_ONBOARDING_OFFICESUITE= "PREFS_ONBOARDING_OFFICESUITE";

    String PREFS_SOFTPHONE_ENABLE= "PREFS_SOFTPHONE_ENABLE";

    String PREFS_SOFTPHONE_USER= "PREFS_SOFTPHONE_USER";

    String PREFS_SOFTPHONE_PASSWORD= "PREFS_SOFTPHONE_PASSWORD";
}
